version: '3.4'

services:
  nodemicroservice:
    image: nodemicroservice
    build:
      context: auth-service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
